# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gooddata_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gooddata_data.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\014gen/go/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13gooddata_data.proto\x12\x05proto\"7\n\x08NodeInfo\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\t\"\x0e\n\x0cResourceInfo\"\x8c\x01\n\x11QueryCustomerInfo\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\x12\n\npublic_key\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\"\n\tnode_info\x18\x06 \x01(\x0b\x32\x0f.proto.NodeInfo\"N\n\x06\x44OInfo\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x12\n\npublic_key\x18\x02 \x01(\t\x12\"\n\tnode_info\x18\x03 \x01(\x0b\x32\x0f.proto.NodeInfo\"{\n\x07MPCInfo\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x12\n\npublic_key\x18\x02 \x01(\t\x12\"\n\tnode_info\x18\x03 \x01(\x0b\x32\x0f.proto.NodeInfo\x12*\n\rresource_info\x18\x04 \x01(\x0b\x32\x13.proto.ResourceInfo\"M\n\tQueryInfo\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07qc_uuid\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x10\n\x08\x64\x61ta_set\x18\x04 \x01(\x03\"i\n\x0cQueryCluster\x12\x12\n\nquery_uuid\x18\x01 \x01(\t\x12\"\n\tmpc_nodes\x18\x02 \x03(\x0b\x32\x0f.proto.NodeInfo\x12!\n\x08\x64o_nodes\x18\x03 \x03(\x0b\x32\x0f.proto.NodeInfo\"\x87\x01\n\x12QueryExecutionInfo\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x0c\x12\x15\n\rstart_time_ns\x18\x03 \x01(\x03\x12\x18\n\x10\x66inished_time_ns\x18\x04 \x01(\x03\x12\"\n\x06status\x18\x05 \x01(\x0e\x32\x12.proto.QueryStatus*:\n\x0bQueryStatus\x12\x10\n\x0cNotCompleted\x10\x00\x12\r\n\tSucceeded\x10\x01\x12\n\n\x06\x46\x61iled\x10\x02\x42\x0eZ\x0cgen/go/protob\x06proto3'
)

_QUERYSTATUS = _descriptor.EnumDescriptor(
  name='QueryStatus',
  full_name='proto.QueryStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NotCompleted', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Succeeded', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=775,
  serialized_end=833,
)
_sym_db.RegisterEnumDescriptor(_QUERYSTATUS)

QueryStatus = enum_type_wrapper.EnumTypeWrapper(_QUERYSTATUS)
NotCompleted = 0
Succeeded = 1
Failed = 2



_NODEINFO = _descriptor.Descriptor(
  name='NodeInfo',
  full_name='proto.NodeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='proto.NodeInfo.uuid', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='proto.NodeInfo.address', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='proto.NodeInfo.port', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=85,
)


_RESOURCEINFO = _descriptor.Descriptor(
  name='ResourceInfo',
  full_name='proto.ResourceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=101,
)


_QUERYCUSTOMERINFO = _descriptor.Descriptor(
  name='QueryCustomerInfo',
  full_name='proto.QueryCustomerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='proto.QueryCustomerInfo.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='proto.QueryCustomerInfo.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='proto.QueryCustomerInfo.uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='proto.QueryCustomerInfo.public_key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='proto.QueryCustomerInfo.email', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_info', full_name='proto.QueryCustomerInfo.node_info', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=244,
)


_DOINFO = _descriptor.Descriptor(
  name='DOInfo',
  full_name='proto.DOInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='proto.DOInfo.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='proto.DOInfo.public_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_info', full_name='proto.DOInfo.node_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=324,
)


_MPCINFO = _descriptor.Descriptor(
  name='MPCInfo',
  full_name='proto.MPCInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='proto.MPCInfo.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='public_key', full_name='proto.MPCInfo.public_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_info', full_name='proto.MPCInfo.node_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resource_info', full_name='proto.MPCInfo.resource_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=449,
)


_QUERYINFO = _descriptor.Descriptor(
  name='QueryInfo',
  full_name='proto.QueryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='proto.QueryInfo.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='qc_uuid', full_name='proto.QueryInfo.qc_uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='proto.QueryInfo.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_set', full_name='proto.QueryInfo.data_set', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=528,
)


_QUERYCLUSTER = _descriptor.Descriptor(
  name='QueryCluster',
  full_name='proto.QueryCluster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_uuid', full_name='proto.QueryCluster.query_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mpc_nodes', full_name='proto.QueryCluster.mpc_nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='do_nodes', full_name='proto.QueryCluster.do_nodes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=635,
)


_QUERYEXECUTIONINFO = _descriptor.Descriptor(
  name='QueryExecutionInfo',
  full_name='proto.QueryExecutionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='proto.QueryExecutionInfo.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='proto.QueryExecutionInfo.result', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time_ns', full_name='proto.QueryExecutionInfo.start_time_ns', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='finished_time_ns', full_name='proto.QueryExecutionInfo.finished_time_ns', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='proto.QueryExecutionInfo.status', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=638,
  serialized_end=773,
)

_QUERYCUSTOMERINFO.fields_by_name['node_info'].message_type = _NODEINFO
_DOINFO.fields_by_name['node_info'].message_type = _NODEINFO
_MPCINFO.fields_by_name['node_info'].message_type = _NODEINFO
_MPCINFO.fields_by_name['resource_info'].message_type = _RESOURCEINFO
_QUERYCLUSTER.fields_by_name['mpc_nodes'].message_type = _NODEINFO
_QUERYCLUSTER.fields_by_name['do_nodes'].message_type = _NODEINFO
_QUERYEXECUTIONINFO.fields_by_name['status'].enum_type = _QUERYSTATUS
DESCRIPTOR.message_types_by_name['NodeInfo'] = _NODEINFO
DESCRIPTOR.message_types_by_name['ResourceInfo'] = _RESOURCEINFO
DESCRIPTOR.message_types_by_name['QueryCustomerInfo'] = _QUERYCUSTOMERINFO
DESCRIPTOR.message_types_by_name['DOInfo'] = _DOINFO
DESCRIPTOR.message_types_by_name['MPCInfo'] = _MPCINFO
DESCRIPTOR.message_types_by_name['QueryInfo'] = _QUERYINFO
DESCRIPTOR.message_types_by_name['QueryCluster'] = _QUERYCLUSTER
DESCRIPTOR.message_types_by_name['QueryExecutionInfo'] = _QUERYEXECUTIONINFO
DESCRIPTOR.enum_types_by_name['QueryStatus'] = _QUERYSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeInfo = _reflection.GeneratedProtocolMessageType('NodeInfo', (_message.Message,), {
  'DESCRIPTOR' : _NODEINFO,
  '__module__' : 'gooddata_data_pb2'
  # @@protoc_insertion_point(class_scope:proto.NodeInfo)
  })
_sym_db.RegisterMessage(NodeInfo)

ResourceInfo = _reflection.GeneratedProtocolMessageType('ResourceInfo', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCEINFO,
  '__module__' : 'gooddata_data_pb2'
  # @@protoc_insertion_point(class_scope:proto.ResourceInfo)
  })
_sym_db.RegisterMessage(ResourceInfo)

QueryCustomerInfo = _reflection.GeneratedProtocolMessageType('QueryCustomerInfo', (_message.Message,), {
  'DESCRIPTOR' : _QUERYCUSTOMERINFO,
  '__module__' : 'gooddata_data_pb2'
  # @@protoc_insertion_point(class_scope:proto.QueryCustomerInfo)
  })
_sym_db.RegisterMessage(QueryCustomerInfo)

DOInfo = _reflection.GeneratedProtocolMessageType('DOInfo', (_message.Message,), {
  'DESCRIPTOR' : _DOINFO,
  '__module__' : 'gooddata_data_pb2'
  # @@protoc_insertion_point(class_scope:proto.DOInfo)
  })
_sym_db.RegisterMessage(DOInfo)

MPCInfo = _reflection.GeneratedProtocolMessageType('MPCInfo', (_message.Message,), {
  'DESCRIPTOR' : _MPCINFO,
  '__module__' : 'gooddata_data_pb2'
  # @@protoc_insertion_point(class_scope:proto.MPCInfo)
  })
_sym_db.RegisterMessage(MPCInfo)

QueryInfo = _reflection.GeneratedProtocolMessageType('QueryInfo', (_message.Message,), {
  'DESCRIPTOR' : _QUERYINFO,
  '__module__' : 'gooddata_data_pb2'
  # @@protoc_insertion_point(class_scope:proto.QueryInfo)
  })
_sym_db.RegisterMessage(QueryInfo)

QueryCluster = _reflection.GeneratedProtocolMessageType('QueryCluster', (_message.Message,), {
  'DESCRIPTOR' : _QUERYCLUSTER,
  '__module__' : 'gooddata_data_pb2'
  # @@protoc_insertion_point(class_scope:proto.QueryCluster)
  })
_sym_db.RegisterMessage(QueryCluster)

QueryExecutionInfo = _reflection.GeneratedProtocolMessageType('QueryExecutionInfo', (_message.Message,), {
  'DESCRIPTOR' : _QUERYEXECUTIONINFO,
  '__module__' : 'gooddata_data_pb2'
  # @@protoc_insertion_point(class_scope:proto.QueryExecutionInfo)
  })
_sym_db.RegisterMessage(QueryExecutionInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
